// ServiceSteps.tsx

import React from 'react';
import Lottie from 'lottie-react';
import { Carousel } from 'react-responsive-carousel';
import "react-responsive-carousel/lib/styles/carousel.min.css";
import one from '../assets/animations/1.json';
import two from '../assets/animations/2.json';
import three from '../assets/animations/3.json';
import four from '../assets/animations/4.json';
import five from '../assets/animations/5.json';
import six from '../assets/animations/6.json';
import seven from '../assets/animations/7.json';
import eight from '../assets/animations/8.json';
import nine from '../assets/animations/9.json';

const services = [
    {
      title: '1. Understanding Your Needs',
      description: 'We start by getting to know your business, your goals, and the challenges you face. This helps us understand where you are and where you want to go.',
      animation: one,
    },
    {
      title: '2. Concepting Ideas',
      description: 'Next, we brainstorm ideas and develop a concrete, actionable plan. We consider different approaches and select the best one based on your specific needs.',
      animation: two,
    },
    {
      title: '3. Designing the Solution',
      description: 'We design a solution tailored to your needs, taking into account user experience, scalability, and future growth.',
      animation: three,
    },
    {
      title: '4. Building the System',
      description: 'Our team of expert developers starts building the system, ensuring it is robust, secure, and efficient.',
      animation: four,
    },
    {
      title: '5. Testing and Refining',
      description: 'We thoroughly test the system, refining and tweaking it as necessary to ensure it meets your needs and expectations.',
      animation: five,
    },
    {
      title: '6. Integrating Systems',
      description: 'We integrate the new system with your existing systems, ensuring they work together seamlessly for maximum efficiency.',
      animation: six,
    },
    {
      title: '7. Training and Support',
      description: 'We provide training and support to help your team get the most out of the new system. We’re here to answer any questions and resolve any issues.',
      animation: seven,
    },
    {
      title: '8. Analysing data for decision making',
      description: 'We analyse the data generated by the system to help you make informed decisions and improve your business processes.',
      animation: eight,
    },
    {
      title: '9. Deploying to Production',
      description: 'Finally, we deploy the system to a production environment, ensuring it runs smoothly and reliably. We monitor the system to ensure it delivers the expected results.',
      animation: nine,
    },
];
  
const ServiceSteps: React.FC = () => {
  const centerSlidePercentage = 50; // Adjust this value to center the selected card

  return (
    <div className="flex flex-col items-center justify-center min-h-screen">
      <h2 className="text-3xl font-bold text-center mb-4">Efficient Software Engineering Services</h2>
      <p className="text-lg text-gray-700 dark:text-gray-300 text-center">
        As a software engineer, I follow a meticulous approach to address your software needs effectively. The following steps outline the process:
      </p>
      <div className="carousel-container">
        <Carousel
          showThumbs={false}
          showStatus={false}
          infiniteLoop
          centerMode
          centerSlidePercentage={centerSlidePercentage}
          autoPlay={false} 
        >
          {services.map((service, index) => (
            <div key={index} className="flex flex-col items-center justify-center my-8 mx-8 p-4 bg-white dark:bg-gray-900 shadow rounded-lg animate__animated animate__slideInLeft">
              <div className="p-4">
                <h2 className="text-4xl mb-8 font-bold text-gray-900 dark:text-gray-200 mb-2">{service.title}</h2>
                <p className="text-base text-gray-600 dark:text-gray-400">{service.description}</p>
              </div>
              <div>
                <Lottie animationData={service.animation} />
              </div>
            </div>
          ))}
        </Carousel>
      </div>
    </div>
  );
};

export default ServiceSteps;