// ServiceSteps.tsx

import React from 'react';
import Lottie from 'lottie-react';
import { Carousel } from 'react-responsive-carousel';
import "react-responsive-carousel/lib/styles/carousel.min.css";
import one from '../assets/animations/1.json';
import two from '../assets/animations/2.json';
import three from '../assets/animations/3.json';
import four from '../assets/animations/4.json';
import five from '../assets/animations/5.json';
import six from '../assets/animations/6.json';
import seven from '../assets/animations/7.json';
import eight from '../assets/animations/8.json';
import nine from '../assets/animations/9.json';

const services = [
  {
    title: '1. Understanding Your Needs',
    description: 'The process begins with a thorough understanding of your business, goals, and challenges. This foundational knowledge guides the journey from where you are to where you want to go.',
    animation: one,
  },
  {
    title: '2. Concepting Ideas',
    description: 'Ideas are then brainstormed and a concrete, actionable plan is developed. Various approaches are considered to ensure the best one is selected for your specific needs.',
    animation: two,
  },
  {
    title: '3. Designing the Solution',
    description: 'A solution tailored to your needs is designed, with careful consideration of user experience, scalability, and future growth.',
    animation: three,
  },
  {
    title: '4. Building the System',
    description: 'The system is then built, with a focus on robustness, security, and efficiency.',
    animation: four,
  },
  {
    title: '5. Testing and Refining',
    description: 'The system undergoes thorough testing, with necessary refinements and tweaks made to ensure it meets your needs and expectations.',
    animation: five,
  },
  {
    title: '6. Integrating Systems',
    description: 'The new system is integrated with your existing systems, ensuring seamless operation for maximum efficiency.',
    animation: six,
  },
  {
    title: '7. Training and Support',
    description: 'Training and support are provided to help your team maximize the benefits of the new system. Any questions are answered and issues resolved.',
    animation: seven,
  },
  {
    title: '8. Analysing data for decision making',
    description: 'Data generated by the system is analyzed to inform decision-making and improve business processes.',
    animation: eight,
  },
  {
    title: '9. Deploying to Production',
    description: 'Finally, the system is deployed to a production environment, with careful monitoring to ensure smooth operation and delivery of expected results.',
    animation: nine,
  },
];

const ServiceSteps: React.FC = () => {
  const centerSlidePercentage = 50; // Adjust this value to center the selected card

  return (
    <div className="flex flex-col items-center justify-center min-h-screen">
      <h2 className="text-3xl font-bold text-center mb-4">Efficient Software Engineering Services</h2>
      <p className="text-lg text-gray-700 dark:text-gray-300 text-center">
      As a dedicated software engineer, my approach is rooted in meticulous planning and execution to effectively meet your software requirements. The process I follow is outlined in the subsequent steps      </p>
      <div className="carousel-container max-w-full overflow-x-auto">
        <Carousel
          showThumbs={false}
          showStatus={false}
          infiniteLoop
          centerMode
          centerSlidePercentage={centerSlidePercentage}
          autoPlay={false} 
        >
          {services.map((service, index) => (
            <div key={index} className="flex flex-col items-center justify-center my-8 mx-2 sm:mx-8 p-4 bg-white dark:bg-gray-900 shadow rounded-lg animate__animated animate__slideInLeft">
              <div className="p-4">
                <h2 className="text-4xl mb-8 font-bold text-gray-900 dark:text-gray-200 mb-2">{service.title}</h2>
                <p className="text-base text-gray-600 dark:text-gray-400">{service.description}</p>
              </div>
              <div>
                <Lottie animationData={service.animation} />
              </div>
            </div>
          ))}
        </Carousel>
      </div>
    </div>
  );
};

export default ServiceSteps;